-- =============================================
-- Task Service 数据库初始化脚本
-- 包含: 异步任务表
-- =============================================

-- 创建异步任务表
CREATE TABLE IF NOT EXISTS `task_async_job` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `task_id` VARCHAR(64) NOT NULL COMMENT '业务任务ID(对外暴露)',
    `task_type` VARCHAR(64) NOT NULL COMMENT '任务类型: summary/extract/report/generate',
    `task_name` VARCHAR(128) DEFAULT NULL COMMENT '任务名称',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态: 0-PENDING 1-QUEUED 2-RUNNING 3-SUCCESS 4-FAILED 5-CANCELLED 6-TIMEOUT',
    `priority` TINYINT NOT NULL DEFAULT 5 COMMENT '优先级: 1-10, 数字越小优先级越高',
    `progress` TINYINT DEFAULT 0 COMMENT '进度百分比(0-100)',
    `progress_detail` VARCHAR(512) DEFAULT NULL COMMENT '进度详情描述',
    `input_params` JSON NOT NULL COMMENT '输入参数',
    `output_result` LONGTEXT COMMENT '输出结果',
    `output_url` VARCHAR(512) DEFAULT NULL COMMENT '输出文件URL',
    `model_id` VARCHAR(64) DEFAULT NULL COMMENT '使用的模型',
    `provider` VARCHAR(32) DEFAULT NULL COMMENT 'AI提供商',
    `prompt_tokens` INT DEFAULT 0 COMMENT '输入token数',
    `completion_tokens` INT DEFAULT 0 COMMENT '输出token数',
    `total_tokens` INT DEFAULT 0 COMMENT '总token数',
    `cost_usd` DECIMAL(10,6) DEFAULT 0.000000 COMMENT '成本(美元)',
    `started_at` DATETIME DEFAULT NULL COMMENT '开始执行时间',
    `completed_at` DATETIME DEFAULT NULL COMMENT '完成时间',
    `cancelled_at` DATETIME DEFAULT NULL COMMENT '取消时间',
    `timeout_at` DATETIME DEFAULT NULL COMMENT '超时时间',
    `retry_count` TINYINT NOT NULL DEFAULT 0 COMMENT '重试次数',
    `max_retry` TINYINT NOT NULL DEFAULT 3 COMMENT '最大重试次数',
    `error_code` VARCHAR(64) DEFAULT NULL COMMENT '错误码',
    `error_msg` TEXT COMMENT '错误信息',
    `stack_trace` TEXT COMMENT '异常堆栈',
    `worker_node` VARCHAR(64) DEFAULT NULL COMMENT '执行节点',
    `mq_message_id` VARCHAR(128) DEFAULT NULL COMMENT 'MQ消息ID',
    `trace_id` VARCHAR(64) DEFAULT NULL COMMENT '链路追踪ID',
    `callback_url` VARCHAR(512) DEFAULT NULL COMMENT '回调URL',
    `callback_status` TINYINT DEFAULT 0 COMMENT '回调状态: 0-未回调 1-成功 2-失败',
    `callback_count` TINYINT DEFAULT 0 COMMENT '回调次数',
    `last_callback_at` DATETIME DEFAULT NULL COMMENT '最后回调时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除: 0-否 1-是',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_task_id` (`task_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_user_status` (`user_id`,`status`),
    KEY `idx_task_type` (`task_type`),
    KEY `idx_created_at` (`created_at`),
    KEY `idx_completed_at` (`completed_at`),
    KEY `idx_trace_id` (`trace_id`),
    KEY `idx_mq_message_id` (`mq_message_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='异步任务表';
