-- billing 服务表：ai_platform 库
-- ============================================================
-- Billing Service Database Initialization Script
-- Version: 1.0.0
-- Date: 2026-05-28
-- ============================================================

USE `ai_platform`;

-- Token消费记录表
CREATE TABLE IF NOT EXISTS `billing_token_usage` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `usage_id` varchar(64) NOT NULL COMMENT '消费记录ID',
  `user_id` bigint unsigned NOT NULL COMMENT '用户ID',
  `conversation_id` bigint unsigned DEFAULT NULL COMMENT '关联会话ID',
  `message_id` bigint unsigned DEFAULT NULL COMMENT '关联消息ID',
  `task_id` bigint unsigned DEFAULT NULL COMMENT '关联任务ID',
  `provider` varchar(32) NOT NULL COMMENT '提供商: openai/deepseek/claude',
  `model_id` varchar(64) NOT NULL COMMENT '模型ID',
  `operation_type` varchar(32) NOT NULL COMMENT '操作类型: chat/completion/embedding',
  `prompt_tokens` int unsigned NOT NULL DEFAULT '0' COMMENT '输入token数',
  `completion_tokens` int unsigned NOT NULL DEFAULT '0' COMMENT '输出token数',
  `total_tokens` int unsigned NOT NULL DEFAULT '0' COMMENT '总token数',
  `prompt_cost` decimal(12,8) NOT NULL DEFAULT '0.00000000' COMMENT '输入成本(USD)',
  `completion_cost` decimal(12,8) NOT NULL DEFAULT '0.00000000' COMMENT '输出成本(USD)',
  `total_cost` decimal(12,8) NOT NULL DEFAULT '0.00000000' COMMENT '总成本(USD)',
  `exchange_rate` decimal(10,6) DEFAULT '7.200000' COMMENT '汇率(USD to CNY)',
  `cost_cny` decimal(12,6) DEFAULT '0.000000' COMMENT '成本(CNY)',
  `latency_ms` int unsigned DEFAULT '0' COMMENT '延迟(毫秒)',
  `error_code` varchar(64) DEFAULT NULL COMMENT '错误码',
  `error_msg` text COMMENT '错误信息',
  `is_billed` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '是否计费: 0-否 1-是',
  `billed_at` datetime DEFAULT NULL COMMENT '计费时间',
  `usage_date` date NOT NULL COMMENT '使用日期(用于分表)',
  `usage_hour` tinyint unsigned NOT NULL COMMENT '使用小时',
  `trace_id` varchar(64) DEFAULT NULL COMMENT '链路追踪ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_usage_id` (`usage_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_user_date` (`user_id`,`usage_date`),
  KEY `idx_conversation_id` (`conversation_id`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_provider_model` (`provider`,`model_id`),
  KEY `idx_usage_date` (`usage_date`),
  KEY `idx_billed_at` (`billed_at`),
  KEY `idx_trace_id` (`trace_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Token消费记录表';

-- 价格配置表
CREATE TABLE IF NOT EXISTS `billing_price_config` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `config_id` varchar(64) NOT NULL COMMENT '配置ID',
  `provider` varchar(32) NOT NULL COMMENT '提供商: openai/deepseek/claude',
  `model_id` varchar(64) NOT NULL COMMENT '模型ID',
  `model_name` varchar(128) DEFAULT NULL COMMENT '模型名称',
  `operation_type` varchar(32) NOT NULL COMMENT '操作类型: chat/completion/embedding',
  `input_price` decimal(12,8) NOT NULL DEFAULT '0.00000000' COMMENT '输入价格(每1K tokens, USD)',
  `output_price` decimal(12,8) NOT NULL DEFAULT '0.00000000' COMMENT '输出价格(每1K tokens, USD)',
  `batch_discount` decimal(5,2) DEFAULT '1.00' COMMENT '批量输入价格折扣',
  `precision` tinyint unsigned DEFAULT '8' COMMENT '计费精度',
  `rounding_mode` varchar(16) DEFAULT 'HALF_UP' COMMENT '计费舍入方式',
  `effective_at` datetime NOT NULL COMMENT '生效时间',
  `expire_at` datetime DEFAULT NULL COMMENT '过期时间',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '状态: 0-禁用 1-启用',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_config_id` (`config_id`),
  KEY `idx_provider_model` (`provider`,`model_id`),
  KEY `idx_operation_type` (`operation_type`),
  KEY `idx_effective_at` (`effective_at`),
  KEY `idx_expire_at` (`expire_at`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='价格配置表';

-- 配额配置表
CREATE TABLE IF NOT EXISTS `billing_quota_config` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `config_id` varchar(64) NOT NULL COMMENT '配置ID',
  `config_name` varchar(128) NOT NULL COMMENT '配置名称',
  `quota_type` tinyint unsigned NOT NULL COMMENT '配额类型: 1-每日token数 2-每月token数 3-总计token数 4-每日请求数 5-存储空间',
  `user_type` tinyint unsigned NOT NULL COMMENT '适用用户类型: 1-普通用户 2-VIP用户 9-管理员',
  `daily_limit` bigint unsigned NOT NULL DEFAULT '0' COMMENT '每日限制(0为无限制)',
  `monthly_limit` bigint unsigned NOT NULL DEFAULT '0' COMMENT '每月限制(0为无限制)',
  `total_limit` bigint unsigned NOT NULL DEFAULT '0' COMMENT '总计限制(0为无限制)',
  `exceed_action` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '超限处理方式: 1-拒绝 2-警告 3-允许但记录',
  `exceed_threshold` tinyint unsigned NOT NULL DEFAULT '120' COMMENT '超限阈值(百分比)',
  `reset_cycle` varchar(16) NOT NULL DEFAULT 'daily' COMMENT '重置周期: daily/monthly/none',
  `reset_day` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '每月重置日',
  `effective_at` datetime NOT NULL COMMENT '生效时间',
  `expire_at` datetime DEFAULT NULL COMMENT '过期时间',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '状态: 0-禁用 1-启用',
  `priority` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '优先级',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_config_id` (`config_id`),
  KEY `idx_quota_type` (`quota_type`),
  KEY `idx_user_type` (`user_type`),
  KEY `idx_effective_at` (`effective_at`),
  KEY `idx_expire_at` (`expire_at`),
  KEY `idx_status` (`status`),
  KEY `idx_priority` (`priority`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='配额配置表';

-- 配额记录表
CREATE TABLE IF NOT EXISTS `billing_quota_record` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `record_id` varchar(64) NOT NULL COMMENT '记录ID',
  `user_id` bigint unsigned NOT NULL COMMENT '用户ID',
  `quota_type` tinyint unsigned NOT NULL COMMENT '配额类型',
  `daily_limit` bigint unsigned NOT NULL DEFAULT '0' COMMENT '每日限制',
  `monthly_limit` bigint unsigned NOT NULL DEFAULT '0' COMMENT '每月限制',
  `total_limit` bigint unsigned NOT NULL DEFAULT '0' COMMENT '总计限制',
  `daily_used` bigint unsigned NOT NULL DEFAULT '0' COMMENT '今日已使用',
  `monthly_used` bigint unsigned NOT NULL DEFAULT '0' COMMENT '本月已使用',
  `total_used` bigint unsigned NOT NULL DEFAULT '0' COMMENT '总计已使用',
  `last_reset_date` date DEFAULT NULL COMMENT '最后重置日期',
  `reset_day` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '每月重置日',
  `effective_at` datetime NOT NULL COMMENT '生效时间',
  `expire_at` datetime DEFAULT NULL COMMENT '过期时间',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '状态: 0-禁用 1-启用',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_id` (`record_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_user_quota_type` (`user_id`,`quota_type`),
  KEY `idx_last_reset_date` (`last_reset_date`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='配额记录表';

-- 账单表
CREATE TABLE IF NOT EXISTS `billing_bill` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `bill_id` varchar(64) NOT NULL COMMENT '账单ID',
  `user_id` bigint unsigned NOT NULL COMMENT '用户ID',
  `bill_no` varchar(64) NOT NULL COMMENT '账单编号',
  `bill_type` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '账单类型: 1-月结账单 2-即时账单',
  `bill_period` tinyint unsigned DEFAULT NULL COMMENT '账单周期: 1-按月 2-按季度 3-按年',
  `bill_start_date` date NOT NULL COMMENT '账单开始日期',
  `bill_end_date` date NOT NULL COMMENT '账单结束日期',
  `bill_due_date` date NOT NULL COMMENT '账单到期日期',
  `total_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '总金额',
  `discount_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '折扣金额',
  `payable_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '应付金额',
  `paid_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '已付金额',
  `tax_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '税额',
  `status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '状态: 0-待支付 1-已支付 2-已逾期 3-部分支付 4-已取消',
  `paid_at` datetime DEFAULT NULL COMMENT '支付时间',
  `pay_method` varchar(32) DEFAULT NULL COMMENT '支付方式',
  `pay_trade_no` varchar(128) DEFAULT NULL COMMENT '支付交易号',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bill_id` (`bill_id`),
  UNIQUE KEY `uk_bill_no` (`bill_no`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_bill_period` (`bill_period`),
  KEY `idx_bill_due_date` (`bill_due_date`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='账单表';

-- 发票表
CREATE TABLE IF NOT EXISTS `billing_invoice` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `invoice_id` varchar(64) NOT NULL COMMENT '发票ID',
  `user_id` bigint unsigned NOT NULL COMMENT '用户ID',
  `invoice_no` varchar(64) DEFAULT NULL COMMENT '发票号码',
  `invoice_type` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '发票类型: 1-增值税专用发票 2-增值税普通发票 3-电子普通发票',
  `title` varchar(256) NOT NULL COMMENT '发票抬头',
  `tax_no` varchar(32) DEFAULT NULL COMMENT '纳税人识别号',
  `bank_name` varchar(128) DEFAULT NULL COMMENT '开户银行',
  `bank_account` varchar(64) DEFAULT NULL COMMENT '银行账号',
  `address` varchar(256) DEFAULT NULL COMMENT '注册地址',
  `phone` varchar(32) DEFAULT NULL COMMENT '注册电话',
  `email` varchar(128) DEFAULT NULL COMMENT '接收邮箱',
  `amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '发票金额',
  `status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '状态: 0-待审核 1-开票中 2-已开票 3-已邮寄 4-已完成 5-已拒绝 6-已作废',
  `applied_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '申请时间',
  `issued_at` datetime DEFAULT NULL COMMENT '开票时间',
  `bill_ids` varchar(1024) DEFAULT NULL COMMENT '关联账单ID列表',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `reject_reason` varchar(512) DEFAULT NULL COMMENT '拒绝原因',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_invoice_id` (`invoice_id`),
  UNIQUE KEY `uk_invoice_no` (`invoice_no`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_applied_at` (`applied_at`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='发票表';

-- 支付表
CREATE TABLE IF NOT EXISTS `billing_payment` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `payment_id` varchar(64) NOT NULL COMMENT '支付ID',
  `user_id` bigint unsigned NOT NULL COMMENT '用户ID',
  `bill_id` varchar(64) NOT NULL COMMENT '账单ID',
  `payment_no` varchar(64) NOT NULL COMMENT '支付单号',
  `payment_type` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '支付类型: 1-账单支付 2-充值 3-退款',
  `channel` tinyint unsigned NOT NULL COMMENT '支付渠道: 1-支付宝 2-微信支付 3-银联',
  `channel_name` varchar(32) DEFAULT NULL COMMENT '渠道名称',
  `amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '支付金额',
  `fee` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '手续费',
  `currency` varchar(8) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '状态: 0-待支付 1-支付成功 2-支付失败 3-已关闭 4-已退款',
  `paid_at` datetime DEFAULT NULL COMMENT '支付时间',
  `expired_at` datetime DEFAULT NULL COMMENT '过期时间',
  `third_trade_no` varchar(128) DEFAULT NULL COMMENT '第三方交易号',
  `payer_info` varchar(512) DEFAULT NULL COMMENT '支付者信息',
  `callback_info` text COMMENT '回调信息',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_id` (`payment_id`),
  UNIQUE KEY `uk_payment_no` (`payment_no`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_bill_id` (`bill_id`),
  KEY `idx_channel` (`channel`),
  KEY `idx_status` (`status`),
  KEY `idx_third_trade_no` (`third_trade_no`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付表';
